# Generated by Django 6.0.1 on 2026-02-03 14:31

import django.db.models.deletion
import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('manufacturer_id', shortuuid.django_fields.ShortUUIDField(alphabet='ABcDeFg1234', db_index=True, length=16, max_length=40, prefix='ID_', primary_key=True, serialize=False)),
                ('manifacturer_name', models.CharField(default='', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', shortuuid.django_fields.ShortUUIDField(alphabet='ABcDeFg1234', db_index=True, length=16, max_length=40, prefix='ID_', primary_key=True, serialize=False)),
                ('product_name', models.CharField(default='', max_length=200)),
                ('product_type', models.CharField(default='Other', max_length=50)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('cost_per_item', models.PositiveIntegerField(default=0)),
                ('manufacturer', models.ForeignKey(on_delete=models.Model, to='items.manufacturer')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('date_ordered', models.DateTimeField(auto_now_add=True)),
                ('total_amoutn', models.PositiveIntegerField(default=0)),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.product')),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_shipped', models.DateTimeField(auto_now_add=True)),
                ('shipment_status', models.CharField(default='Recived', max_length=25)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.product')),
            ],
        ),
    ]
