# Generated by Django 6.0.1 on 2026-02-03 14:34

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='manufacturer_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='ABcDeFg1234', db_index=True, editable=False, length=16, max_length=40, prefix='ID_', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='ABcDeFg1234', db_index=True, editable=False, length=16, max_length=40, prefix='ID_', primary_key=True, serialize=False),
        ),
    ]
