# Generated by Django 6.0.1 on 2026-02-03 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_alter_manufacturer_manufacturer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('Perishable Goods', 'Perishable Goods'), ('Non-Perishable Goods', 'Non-Perishable Goods'), ('Consumable Goods', 'Consumable Goods'), ('Raw Materials', 'Raw Materials'), ('Other', 'Other')], default='Other', max_length=50),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='shipment_status',
            field=models.CharField(choices=[('On-Transit', 'On-Transit'), ('Recieved', 'Recieved')], default='Recived', max_length=25),
        ),
    ]
