# Generated by Django 6.0.1 on 2026-02-04 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_alter_product_product_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manufacturer',
            old_name='manifacturer_name',
            new_name='manufacturer_name',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='total_amoutn',
            new_name='total_amount',
        ),
        migrations.AlterField(
            model_name='shipment',
            name='shipment_status',
            field=models.CharField(choices=[('On-Transit', 'On-Transit'), ('Received', 'Received')], default='Received', max_length=25),
        ),
    ]
