# Generated by Django 6.0.1 on 2026-02-04 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_rename_manifacturer_name_manufacturer_manufacturer_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manufacturer',
            old_name='manufacturer_name',
            new_name='manifacturer_name',
        ),
    ]
